export enum DbTables {
  encryption = 'encryption',
  permissions = 'permissions',
  profiles = 'profiles',
  roles = 'roles',
  sessions = 'sessions',
  users = 'users',
  usersRestorePasswords = 'users-restore-passwords',
  animals = 'animals',
  people = 'people',
  clinics = 'clinics',
  connections = 'connections',
  bankAccounts = 'bank_accounts',
  financeIncomingGoals = 'finance_incoming_goals',
  financeOutgoingPurposes = 'finance_outgoing_purposes',
  financeIncomingReports = 'finance_incoming_reports',
  financeOutgoingReports = 'finance_outgoing_reports',
  financeDebtReports = 'finance_debt_reports',
  reportsFinance = 'reports_finance',
  reportsStuff = 'reports_stuff',
  inventoryStorage = 'inventory_storage',
  inventoryCategories = 'inventory_categories',
  reportsInventory = 'reports_inventory',
}
