export enum DbTables {
  encryption = 'encryption',
  permissions = 'permissions',
  profiles = 'profiles',
  roles = 'roles',
  sessions = 'sessions',
  users = 'users',
  usersRestorePasswords = 'users-restore-passwords',
  animals = 'animals',
  people = 'people',
  clinics = 'clinics',
  connections = 'connections',
  bankAccounts = 'bank_accounts',
  financeCategories = 'finance_categories',
  financeIncomingReports = 'finance_incoming_reports',
  financeOutgoingReports = 'finance_outgoing_reports',
  financeDebtReports = 'finance_debt_reports',
  reportsStuff = 'reports_stuff',
  inventoryStorage = 'inventory_storage',
  inventoryCategories = 'inventory_categories',
  inventoryItems = 'inventory_items',
  inventoryConsumables = 'inventory_consumables',
  inventoryAssets = 'inventory_assets',
  inventoryTransactions = 'inventory_transactions',
  reportsInventory = 'reports_inventory',
  volunteerActs = 'volunteer_acts',
  volunteerCategories = 'volunteer_category',
}
